### ISSUE TITLE
libcfitsio.dylib  missing and no known rule to make it

### ISSUE THREAD

**Issue by JerryBlack** [rlancaste/kstars-on-osx-craft#8]
Not sure what I've done wrong, but libcfitsio.dylib isn't created/available for me..

Here is the compile output

[https://www.dropbox.com/s/q5itkeclqxe016m/libcfitsio.dylib.txt?dl=0](https://www.dropbox.com/s/q5itkeclqxe016m/libcfitsio.dylib.txt?dl=0)

**Comment by rlancaste** [comment]
I would say nothing, someone just made a change to the cfitsio recipe.  I’m trying to merge all my custom recipes into the actual craft recipes so we can build kstars on Mac there instead of having to do so much custom stuff to get it.  Then we could get daily builds too.  Also other people would be able to fix issues as well.  But that does come with the drawback that things might break more often since other people can change it.  I just made a comment about the change yesterday:

https://invent.kde.org/packaging/craft-blueprints-kde/-/commit/3c93e07e466f49e082ad1d70e3e47cb9d7730335#note_373493

we will see if that helps get it changed.

**Comment by rlancaste** [comment]
If you want to get past this and not wait, you can edit the cfitsio recipe and just run that and install cfitsio and run my script again.

**Comment by rlancaste** [comment]
Sorry, if you want to know how to do this, just edit the file:

~/AstroRoot/craft-root/etc/blueprints/locations/craft-blueprints-kde/libs/cfitsio/cfitsio.py

so that it says "-DBUILD_SHARED_LIBS=ON" not OFF

and then type this in terminal:

cd ~/AstroRoot/craft-root/
source ~/AstroRoot/craft-root/craft/craftenv.sh
craft -vi libs/cfitsio

**Comment by JerryBlack** [comment]
Thanks!

That worked of course.

The script now stumbles on …

-- Build files have been written to: /Users/jerryblack/AstroRoot/craft-root/build/kde/applications/kstars/work/build
executing command: /Users/jerryblack/AstroRoot/craft-root/dev-utils/bin/ninja -j 16
ninja: error: '/Users/jerryblack/AstroRoot/craft-root/lib/libwcs.dylib', needed by 'bin/kstars.app/Contents/MacOS/kstars', missing and no known rule to make it
Action: compile for kde/applications/kstars:master FAILED
*** Craft all failed: kde/applications/kstars after 9 seconds ***
fatal error: package kde/applications/kstars all failed
Craft stopped with out completing ['kde/applications/kstars']

I tried to find the craft logic for libwcs  but haven’t been successful in finding/fixing that dependency yet.

I will git pull again this morning, and do some further searching.   Craft appears to be a foreign art form ;)

Cheers
  Jerry

**Comment by JerryBlack** [comment]
As of 2022/01/11 a complete reinstall has solved this (and the libwcs.dylib issue) for me using the updates craft sources.
